import ExcelJS from "exceljs";
import type { ActivityReportMeta } from "../generateActivityReport";
import { DOLLAR_SIGN_NUMBER_FORMAT, QUANTITY_NUMBER_FORMAT, TABLE_HEADER_ROW, TEXT_FORMAT } from "../../config";
import { currentTime, formatDate } from "~/utils/localDateString";
import type { CiAndRealizationData } from "~/server/api/routers/reports/_types/commercialActivityReport";

const CI_AND_REALIZATION_TABLE_COLUMN_COUNT = 12;

const ciAndRealizationTableColumns = [
    { key: 'buyer_name', width: 25 },
    { key: 'exfactory_dates', width: 15 },
    { key: 'rdl_invoice', width: 25 },
    { key: 'rdl_invoice_date', width: 15 },
    { key: 'rdl_invoice_quantity', width: 15 },
    { key: 'rdl_invoice_value', width: 20 },
    { key: 'fdbc_no', width: 25 },
    { key: 'document_submission_date', width: 15 },
    { key: 'ci_no', width: 30 },
    { key: 'ci_date', width: 15 },
    { key: 'realized_amount', width: 20 },
    { key: 'realized_date', width: 15 },
]

const ciAndRealizationTableHeader = [
    'Buyer Name',
    'Exfactory Dates',
    'Invoice',
    'Invoice Date',
    'Invoice Quantity',
    'Invoice Value',
    'Document Submission',
    'Document Submission Date',
    'Commission Invoice',
    'Commission Invoice Date',
    'Realized Amount',
    'Realized Date'
]

interface CiAndRealizationWorkSheetProps {
    workbook: ExcelJS.Workbook;
    ciAndRealizationData: CiAndRealizationData[];
    reportMeta: ActivityReportMeta;
}

export const generateCiAndRealizationWorkSheet = (Props: CiAndRealizationWorkSheetProps) => {
    const { workbook, ciAndRealizationData, reportMeta } = Props;

    const ciAndRealizationWorksheet = workbook.addWorksheet("CI & Realization", {
        views: [
            {
                state: "frozen",
                ySplit: TABLE_HEADER_ROW,
            },
        ],
    });

    ciAndRealizationWorksheet.columns = ciAndRealizationTableColumns;

    ciAndRealizationWorksheet.mergeCells(1, 1, 1, 6);
    ciAndRealizationWorksheet.mergeCells(2, 1, 2, 2);
    ciAndRealizationWorksheet.mergeCells(3, 1, 3, 2);
    ciAndRealizationWorksheet.mergeCells(4, 1, 4, 2);

    ciAndRealizationWorksheet.getCell("A1").value = `Post-Exfactory Commercial Activity Report`;
    ciAndRealizationWorksheet.getCell("A2").value = `Date Range: ${formatDate(reportMeta.fromDate)} to ${formatDate(reportMeta.toDate)}`;
    ciAndRealizationWorksheet.getCell("A3").value = `Generated by: ${reportMeta.generatedBy}`;
    ciAndRealizationWorksheet.getCell("A4").value = `Generated on: ${formatDate(new Date())} at ${currentTime}`;

    ciAndRealizationWorksheet.getRow(1).font = {
        bold: true,
        size: 20,
        color: { argb: "FF1F1F1F" },
    };

    ciAndRealizationWorksheet.getRow(2).font = {
        size: 11,
        color: { argb: "FF4B4B4B" },
    };

    ciAndRealizationWorksheet.getRow(3).font = {
        size: 11,
        color: { argb: "FF4B4B4B" },
    };

    ciAndRealizationWorksheet.getRow(4).font = {
        size: 11,
        color: { argb: "FF4B4B4B" },
    };

    ciAndRealizationWorksheet.getRow(6).font = {
        bold: true,
        color: { argb: "FFFFFFFF" },
    };
    
    ciAndRealizationWorksheet.getRow(6).fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "1F4E78" },
    };

    ciAndRealizationWorksheet.getRow(TABLE_HEADER_ROW).values = [...ciAndRealizationTableHeader];

    ciAndRealizationWorksheet.autoFilter = {
        from: "A6",
        to: "AC6",
    };

    ciAndRealizationWorksheet.getRow(1).height = 22;
    ciAndRealizationWorksheet.getRow(2).height = 18;
    ciAndRealizationWorksheet.getRow(3).height = 18;
    ciAndRealizationWorksheet.getRow(6).height = 20;
    
    ciAndRealizationData.forEach((row) => ciAndRealizationWorksheet.addRow(row));

    // Remove borders from the first 4 rows and all columns
    for (let row = 1; row <= 5; row++) {
        for (let col = 1; col <= CI_AND_REALIZATION_TABLE_COLUMN_COUNT; col++) {
            const cell = ciAndRealizationWorksheet.getCell(row, col);
            cell.fill = {
                type: "pattern",
                pattern: "solid",
                fgColor: { argb: "FFFFFF" },
            };
        }
    }

    // Quantity columns
    ["E"].forEach((col) => {
        ciAndRealizationWorksheet.getColumn(col).numFmt = QUANTITY_NUMBER_FORMAT;
    });

    // Currency columns
    ["F", "K"].forEach((col) => {
        ciAndRealizationWorksheet.getColumn(col).numFmt = DOLLAR_SIGN_NUMBER_FORMAT;
    });

    ["A", "B", "C", "D", "G", "H", "I", "J", "L"].forEach((col) => {
        ciAndRealizationWorksheet.getColumn(col).numFmt = TEXT_FORMAT;
    });

    const totalCiAndRealizationRow = ciAndRealizationWorksheet.addRow({
        buyer_name: "Total",
        rdl_invoice_quantity: { formula: `SUBTOTAL(109,E${TABLE_HEADER_ROW + 1}:E${ciAndRealizationWorksheet.rowCount})` },
        rdl_invoice_value: { formula: `SUBTOTAL(109,F${TABLE_HEADER_ROW + 1}:F${ciAndRealizationWorksheet.rowCount})` },
        realized_amount: { formula: `SUBTOTAL(109,K${TABLE_HEADER_ROW + 1}:K${ciAndRealizationWorksheet.rowCount})` },
    });

    totalCiAndRealizationRow.font = {
        bold: true,
    };

    ciAndRealizationWorksheet.eachRow((row) => {
        row.alignment = {
            vertical: "middle",
            wrapText: false,
        };
    });
}
  