import ExcelJS from "exceljs";
import type { ActivityReportMeta } from "../generateActivityReport";
import { DOLLAR_SIGN_NUMBER_FORMAT, QUANTITY_NUMBER_FORMAT, TABLE_HEADER_ROW, TEXT_FORMAT } from "../../config";
import { currentTime, formatDate } from "~/utils/localDateString";
import type { FactoryInvoiceData } from "~/server/api/routers/reports/_types/commercialActivityReport";

const FACTORY_PAYMENT_TABLE_COLUMN_COUNT = 12;

const factoryPaymentTableColumns = [
    { key: 'buyer_name', width: 25 }, 
    { key: 'exfactory_dates', width: 15 }, 
    { key: 'factory_name', width: 25 }, 
    { key: 'lc_no', width: 25 }, 
    { key: 'sales_contract_no', width: 25 }, 
    { key: 'factory_invoice', width: 25 }, 
    { key: 'factory_invoice_date', width: 15 }, 
    { key: 'factory_invoice_quantity', width: 15 }, 
    { key: 'factory_invoice_value', width: 20 }, 
    { key: 'fdbc_no', width: 30 }, 
    { key: 'factory_payment', width: 25 }, 
    { key: 'factory_payment_date', width: 15 }, 
]

const factoryPaymentTableHeader = [
    'Buyer Name',
    'Exfactory Dates',
    'Factory Name',
    'LC No',
    'Sales Contract No',
    'Factory Invoice',
    'Factory Invoice Date',
    'Factory Invoice Quantity',
    'Factory Invoice Value',
    'Document Submission',
    'Factory Payment',
    'Payment Date'
]

interface FactoryPaymentWorkSheetProps {
    workbook: ExcelJS.Workbook;
    factoryInvoiceData: FactoryInvoiceData[];
    reportMeta: ActivityReportMeta;
}

export const generateFactoryPaymentWorkSheet = (Props: FactoryPaymentWorkSheetProps) => {
    const { workbook, factoryInvoiceData, reportMeta } = Props;

    // Factory Payment Worksheet
    const factoryPaymentWorksheet = workbook.addWorksheet("Factory Payment", {
        views: [
            {
                state: "frozen",
                ySplit: TABLE_HEADER_ROW,
            },
        ],
    });

    factoryPaymentWorksheet.columns = factoryPaymentTableColumns;

    factoryPaymentWorksheet.mergeCells(1, 1, 1, 6);
    factoryPaymentWorksheet.mergeCells(2, 1, 2, 2);
    factoryPaymentWorksheet.mergeCells(3, 1, 3, 2);
    factoryPaymentWorksheet.mergeCells(4, 1, 4, 2);

    factoryPaymentWorksheet.getCell("A1").value = `Post-Exfactory Commercial Activity Report`;
    factoryPaymentWorksheet.getCell("A2").value = `Date Range: ${formatDate(reportMeta.fromDate)} to ${formatDate(reportMeta.toDate)}`;
    factoryPaymentWorksheet.getCell("A3").value = `Generated by: ${reportMeta.generatedBy}`;
    factoryPaymentWorksheet.getCell("A4").value = `Generated on: ${formatDate(new Date())} at ${currentTime}`;

    factoryPaymentWorksheet.getRow(1).font = {
        bold: true,
        size: 20,
        color: { argb: "FF1F1F1F" },
    };

    factoryPaymentWorksheet.getRow(2).font = {
        size: 11,
        color: { argb: "FF4B4B4B" },
    };

    factoryPaymentWorksheet.getRow(3).font = {
        size: 11,
        color: { argb: "FF4B4B4B" },
    };

    factoryPaymentWorksheet.getRow(4).font = {
        size: 11,
        color: { argb: "FF4B4B4B" },
    };

    factoryPaymentWorksheet.getRow(6).font = {
        bold: true,
        color: { argb: "FFFFFFFF" },
    };
    
    factoryPaymentWorksheet.getRow(6).fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "1F4E78" },
    };

    factoryPaymentWorksheet.getRow(TABLE_HEADER_ROW).values = [...factoryPaymentTableHeader];

    factoryPaymentWorksheet.autoFilter = {
        from: "A6",
        to: "AC6",
    };

    factoryPaymentWorksheet.getRow(1).height = 22;
    factoryPaymentWorksheet.getRow(2).height = 18;
    factoryPaymentWorksheet.getRow(3).height = 18;
    factoryPaymentWorksheet.getRow(6).height = 20;
    
    factoryInvoiceData.forEach((row) => factoryPaymentWorksheet.addRow(row));

    // Remove borders from the first 4 rows and all columns
    for (let row = 1; row <= 5; row++) {
        for (let col = 1; col <= FACTORY_PAYMENT_TABLE_COLUMN_COUNT; col++) {
            const cell = factoryPaymentWorksheet.getCell(row, col);
            cell.fill = {
                type: "pattern",
                pattern: "solid",
                fgColor: { argb: "FFFFFF" },
            };
        }
    }

    // Quantity columns
    ["H"].forEach((col) => {
        factoryPaymentWorksheet.getColumn(col).numFmt = QUANTITY_NUMBER_FORMAT;
    });

    // Currency columns
    ["I", "K"].forEach((col) => {
        factoryPaymentWorksheet.getColumn(col).numFmt = DOLLAR_SIGN_NUMBER_FORMAT;
    });

    ["A", "B", "C", "D", "E", "F", "G", "J", "L"].forEach((col) => {
        factoryPaymentWorksheet.getColumn(col).numFmt = TEXT_FORMAT;
    });

    const totalFactoryInvoiceRow = factoryPaymentWorksheet.addRow({
        buyer_name: "Total",
        factory_invoice_quantity: { formula: `SUBTOTAL(109,H${TABLE_HEADER_ROW + 1}:H${factoryPaymentWorksheet.rowCount})` },
        factory_invoice_value: { formula: `SUBTOTAL(109,I${TABLE_HEADER_ROW + 1}:I${factoryPaymentWorksheet.rowCount})` },
        factory_payment: { formula: `SUBTOTAL(109,K${TABLE_HEADER_ROW + 1}:K${factoryPaymentWorksheet.rowCount})` },
    });

    totalFactoryInvoiceRow.font = {
        bold: true,
    };

    factoryPaymentWorksheet.eachRow((row) => {
        row.alignment = {
            vertical: "middle",
            wrapText: false,
        };
    });
}