import ExcelJS from "exceljs";
import { DOLLAR_SIGN_NUMBER_FORMAT, QUANTITY_NUMBER_FORMAT, TABLE_HEADER_ROW, TEXT_FORMAT } from "../../config";
import { currentTime, formatDate } from "~/utils/localDateString";
import type { ActivityReportMeta } from "../generateActivityReport";
import type { PoWiseData } from "~/server/api/routers/reports/_types/commercialActivityReport";

const PO_WISE_TABLE_COLUMN_COUNT = 18;

const poWiseTableColumns = [
    { key: 'buyer_name', width: 25 },
    { key: 'factory_name', width: 25 },
    { key: 'buyer_po', width: 15 },
    { key: 'exfactory_nos', width: 15 },
    { key: 'exfactory_dates', width: 15 },
    { key: 'shipment_quantity', width: 15 },
    { key: 'factory_invoice', width: 25 },
    { key: 'factory_invoice_date', width: 15 },
    { key: 'factory_invoice_quantity', width: 15 },
    { key: 'factory_invoice_value', width: 20 },
    { key: 'lc_no', width: 25 },
    { key: 'sales_contract_no', width: 25 },
    { key: 'rdl_invoice', width: 25 },
    { key: 'rdl_invoice_date', width: 15 },
    { key: 'rdl_invoice_quantity', width: 15 },
    { key: 'rdl_invoice_value', width: 20 },
    { key: 'fdbc_no', width: 25 },
    { key: 'fdbc_date', width: 15 }
]

const poWiseTableHeader = [
    'Buyer Name',
    'Factory Name',
    'Buyer PO',
    'Exfactory Nos',
    'Exfactory Dates',
    'Shipment Quantity',
    'Factory Invoice',
    'Factory Invoice Date',
    'Factory Invoice Quantity',
    'Factory Invoice Value',
    'LC No',
    'Sales Contract No',
    'Invoice',
    'Invoice Date',
    'Invoice Quantity',
    'Invoice Value',
    'FDBC No',
    'FDBC Date'
]

interface PoWiseDataWorkSheetProps {
    workbook: ExcelJS.Workbook;
    poWiseData: PoWiseData[];
    reportMeta: ActivityReportMeta;
}

export const generatePoWiseDataWorkSheet = (Props: PoWiseDataWorkSheetProps) => {
    const { workbook, poWiseData, reportMeta } = Props;

    const poWiseWorksheet = workbook.addWorksheet("Po Wise Data", {
        views: [
            {
                state: "frozen",
                ySplit: TABLE_HEADER_ROW,
            },
        ],
    });

    poWiseWorksheet.columns = poWiseTableColumns;

    poWiseWorksheet.mergeCells(1, 1, 1, 6);
    poWiseWorksheet.mergeCells(2, 1, 2, 2);
    poWiseWorksheet.mergeCells(3, 1, 3, 2);
    poWiseWorksheet.mergeCells(4, 1, 4, 2);

    poWiseWorksheet.getCell("A1").value = `Post-Exfactory Commercial Activity Report`;
    poWiseWorksheet.getCell("A2").value = `Date Range: ${formatDate(reportMeta.fromDate)} to ${formatDate(reportMeta.toDate)}`;
    poWiseWorksheet.getCell("A3").value = `Generated by: ${reportMeta.generatedBy}`;
    poWiseWorksheet.getCell("A4").value = `Generated on: ${formatDate(new Date())} at ${currentTime}`;

    poWiseWorksheet.getRow(1).font = {
        bold: true,
        size: 20,
        color: { argb: "FF1F1F1F" },
    };

    poWiseWorksheet.getRow(2).font = {
        size: 11,
        color: { argb: "FF4B4B4B" },
    };

    poWiseWorksheet.getRow(3).font = {
        size: 11,
        color: { argb: "FF4B4B4B" },
    };

    poWiseWorksheet.getRow(4).font = {
        size: 11,
        color: { argb: "FF4B4B4B" },
    };

    poWiseWorksheet.getRow(6).font = {
        bold: true,
        color: { argb: "FFFFFFFF" },
    };
    
    poWiseWorksheet.getRow(6).fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "1F4E78" },
    };

    poWiseWorksheet.getRow(TABLE_HEADER_ROW).values = [...poWiseTableHeader];

    poWiseWorksheet.autoFilter = {
        from: "A6",
        to: "AC6",
    };

    poWiseWorksheet.getRow(1).height = 22;
    poWiseWorksheet.getRow(2).height = 18;
    poWiseWorksheet.getRow(3).height = 18;
    poWiseWorksheet.getRow(6).height = 20;
    
    poWiseData.forEach((row) => poWiseWorksheet.addRow(row));

    // Remove borders from the first 4 rows and all columns
    for (let row = 1; row <= 5; row++) {
        for (let col = 1; col <= PO_WISE_TABLE_COLUMN_COUNT; col++) {
            const cell = poWiseWorksheet.getCell(row, col);
            cell.fill = {
                type: "pattern",
                pattern: "solid",
                fgColor: { argb: "FFFFFF" },
            };
        }
    }

    // Quantity columns
    ["F", "I", "O"].forEach((col) => {
        poWiseWorksheet.getColumn(col).numFmt = QUANTITY_NUMBER_FORMAT;
    });

    // Currency columns
    ["J", "P"].forEach((col) => {
        poWiseWorksheet.getColumn(col).numFmt = DOLLAR_SIGN_NUMBER_FORMAT;
    });

    ["A", "B", "C", "D", "E", "G", "H", "K", "L", "M", "N", "Q", "R"].forEach((col) => {
        poWiseWorksheet.getColumn(col).numFmt = TEXT_FORMAT;
    });

    const totalRow = poWiseWorksheet.addRow({
        buyer_name: "Total",
        shipment_quantity: { formula: `SUBTOTAL(109,F${TABLE_HEADER_ROW + 1}:F${poWiseWorksheet.rowCount})` },
        factory_invoice_quantity: { formula: `SUBTOTAL(109,I${TABLE_HEADER_ROW + 1}:I${poWiseWorksheet.rowCount})` },
        factory_invoice_value: { formula: `SUBTOTAL(109,J${TABLE_HEADER_ROW + 1}:J${poWiseWorksheet.rowCount})` },
        rdl_invoice_quantity: { formula: `SUBTOTAL(109,O${TABLE_HEADER_ROW + 1}:O${poWiseWorksheet.rowCount})` },
        rdl_invoice_value: { formula: `SUBTOTAL(109,P${TABLE_HEADER_ROW + 1}:P${poWiseWorksheet.rowCount})` },
    });

    totalRow.font = {
        bold: true,
    };

    poWiseWorksheet.eachRow((row) => {
        row.alignment = {
            vertical: "middle",
            wrapText: false,
        };
    });
}