import ExcelJS from "exceljs";
import { formatDate } from "~/utils/localDateString";
import { DOLLAR_SIGN_NUMBER_FORMAT, QUANTITY_NUMBER_FORMAT, TEXT_FORMAT } from "../config";
import type { OrderSummaryReportRow } from "~/server/api/routers/reports/_types/orderSummaryReport";

const TABLE_HEADER_ROW = 6;
const TABLE_COLUMN_COUNT = 29;

const tableHeaders = [
    "Order References",
    "Factory",
    "Buyer",
    "Brand",
    "Department",
    "Size",
    "Season",
    "Style",
    "Product Type",
    "Product",
    "Colors",
    "Fabric",
    "Fabric Supplier",
    "Buyer PO",
    "Order Date",
    "Exfactory Date",
    "Actual Exfactory",
    "Handover Date",
    "ETD",
    "Lot Qty",
    "Delivery Qty",
    "FOB Rate",
    "Factory Rate",
    "PO Close",
    "Order Value",
    "Delivered Value",
    "Factory Order Value",
    "Factory Delivery Value",
    "Team",
];

const currentTime = new Date().toLocaleTimeString('en-US', {
  hour: '2-digit',
  minute: '2-digit',
  hour12: true
});

interface ReportMeta {
    base: string;
    fromDate: string;
    toDate: string;
    generatedBy: string;
}

const toSentenceCase = (str: string) => {
    return str.toLowerCase().replace(/\b\w/g, char => char.toUpperCase());
}

export const generateOrderSummaryExcel = async (rows: OrderSummaryReportRow[], reportMeta: ReportMeta) => {
    const workbook = new ExcelJS.Workbook();

    workbook.creator = reportMeta.generatedBy;
    workbook.created = new Date();
    workbook.company = "Renaissance Designs Limited";
    workbook.subject = "Order Summary Report";
    workbook.title = "Order Summary Report";
    workbook.category = "Merchandising Reports";
    workbook.manager = "Nexus ERP";

    const worksheet = workbook.addWorksheet("Order Summary", {
        views: [
            {
                state: "frozen",
                ySplit: TABLE_HEADER_ROW,
            },
        ],
    });

    worksheet.columns = [
        { key: "ORDER_NO", width: 25 },
        { key: "FACTORY_NAME", width: 25 },
        { key: "BUYER_NAME", width: 25 },
        { key: "BRAND", width: 18 },
        { key: "DEPARTMENT", width: 18 },
        { key: "SIZE", width: 12 },
        { key: "SEASON_NAME", width: 18 },
        { key: "STYLE", width: 20 },
        { key: "PRODUCT_TYPE", width: 20 },
        { key: "PRODUCT", width: 20 },
        { key: "COLORS", width: 30 },
        { key: "FABRIC", width: 35 },
        { key: "FABRIC_SUPPLIER", width: 25 },
        { key: "BUYER_PO", width: 20 },
        { key: "ORDER_DATE", width: 15 },
        { key: "EXFACTORY_DATE", width: 15 },
        { key: "ACTUAL_EXFACTORY_DATE", width: 25 },
        { key: "HANDOVER_DATE", width: 15 },
        { key: "ETD_DATE", width: 15 },
        { key: "LOT_QUANTITY", width: 15 },
        { key: "DELIVERY_QUANTITY", width: 15 },
        { key: "FOB_RATE", width: 15 },
        { key: "FACTORY_RATE", width: 15 },
        { key: "PO_CLOSE", width: 12 },
        { key: "ORDER_RDL_VALUE", width: 18 },
        { key: "DELIVERED_RDL_VALUE", width: 20 },
        { key: "FACTORY_ORDER_VALUE", width: 20 },
        { key: "FACTORY_DELIVERY_VALUE", width: 22 },
        { key: "TEAM_NAME", width: 20 },
    ];

    worksheet.mergeCells(1, 1, 1, 6);
    worksheet.mergeCells(2, 1, 2, 2);
    worksheet.mergeCells(3, 1, 3, 2);
    worksheet.mergeCells(4, 1, 4, 2);

    worksheet.getCell("A1").value = `Order Summary Report based on ${toSentenceCase(reportMeta.base || '')} date`;
    worksheet.getCell("A2").value = `Date Range: ${formatDate(reportMeta.fromDate)} to ${formatDate(reportMeta.toDate)}`;
    worksheet.getCell("A3").value = `Generated by: ${reportMeta.generatedBy}`;
    worksheet.getCell("A4").value = `Generated on: ${formatDate(new Date())} at ${currentTime}`;

    worksheet.getRow(1).font = {
        bold: true,
        size: 20,
        color: { argb: "FF1F1F1F" },
    };

    worksheet.getRow(2).font = {
        size: 11,
        color: { argb: "FF4B4B4B" },
    };

    worksheet.getRow(3).font = {
        size: 11,
        color: { argb: "FF4B4B4B" },
    };

    worksheet.getRow(4).font = {
        size: 11,
        color: { argb: "FF4B4B4B" },
    };

    worksheet.getRow(6).font = {
        bold: true,
        color: { argb: "FFFFFFFF" },
    };

    worksheet.getRow(6).fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "1F4E78" },
    };

    worksheet.getRow(TABLE_HEADER_ROW).values = [...tableHeaders];

    worksheet.autoFilter = {
        from: "A6",
        to: "AC6",
    };

    worksheet.getRow(1).height = 22;
    worksheet.getRow(2).height = 18;
    worksheet.getRow(3).height = 18;
    worksheet.getRow(6).height = 20;

    rows.forEach((row) => worksheet.addRow(row));

    // Quantity columns
    ["T", "U"].forEach((col) => {
        worksheet.getColumn(col).numFmt = QUANTITY_NUMBER_FORMAT;
    });

    // Currency columns
    ["V", "W", "Y", "Z", "AA", "AB"].forEach((col) => {
        worksheet.getColumn(col).numFmt = DOLLAR_SIGN_NUMBER_FORMAT;
    });

    // Boolean column
    worksheet.getColumn("X").alignment = {
        horizontal: "center",
    };

    // Remove borders from the first 4 rows and all columns
    for (let row = 1; row <= 5; row++) {
        for (let col = 1; col <= TABLE_COLUMN_COUNT; col++) {
            const cell = worksheet.getCell(row, col);
            cell.fill = {
                type: "pattern",
                pattern: "solid",
                fgColor: { argb: "FFFFFF" },
            };
        }
    }

    ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "X", "AC"].forEach((col) => {
        worksheet.getColumn(col).numFmt = TEXT_FORMAT;
    });

    worksheet.eachRow((row) => {
        row.alignment = {
            vertical: "middle",
            wrapText: false,
        };
    });

    return await workbook.xlsx.writeBuffer();
};
