export const tableFormColumns = [
    { key: 'style', label: 'Style' },
    { key: 'po', label: 'PO' },
    { key: 'destination', label: 'Destination' },
    { key: 'size', label: 'Size' },
    { key: 'order_quantity', label: 'Order Quantity' },
    { key: 'rdl_fob', label: 'FOB' },
    { key: 'factory_fob', label: 'Factory FOB' },
    { key: 'rdl_value', label: 'Value' },
    { key: 'factory_value', label: 'Factory Value' },
    { key: 'margin_per_piece', label: 'Margin Per Piece' },
    { key: 'commission_value', label: 'Commission Value' },
    { key: 'commission_percentage', label: 'Commission Percentage' },
    { key: 'dhaka_commission_percentage', label: 'Dhaka Commission Percentage' },
    { key: 'dhaka_commission_amount', label: 'Dhaka Commission Value' },
    { key: 'overseas_commission_percentage', label: 'Overseas Commission Percentage' },
    { key: 'overseas_commission_amount', label: 'Overseas Commission Value' },
    { key: 'others_commission_percentage', label: 'Others Commission Percentage' },
    { key: 'others_commission_amount', label: 'Others Commission Value' },
]